<div id="header">
{$page_title}
</div>

<div id="main">
    <aside id="sidemenu">
        <ul>
            <li><a href="{jurl "test~default:index"}">Home</a></li>
            <li><a href="{jurl "news~default:index"}">News</a></li>
            <li><a href="{jurl "news~default:rss"}">News rss</a></li>
        </ul>
    </aside>
    <section id="content">
        {$MAIN}
    </section>
</div>


<div id="footer">
    page HTML generated by {@jelix~jelix.framework.name@}
</div>